### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Techmj** [team2059/Max-Quordlepleen#1]
- [ ] Check that trackWidth and wheelBase don't need to be switched
- [ ] 3 note auto
- [ ] 2 note auto front and side autos
- [ ] figure out how to get alliance color and select speaker position and set apriltag to chase
- [ ] amp scoring buttons
- [ ] shooter preset buttons
- [ ] auto align/aim to speaker
- [ ] use robot pose to calculate distance to speaker when camera reading isn't present
- [ ] make tilt and rev up in parallel
- [ ] Test climb
- [ ] Test trap
- [ ] Create auto combinations
- [ ] [How does your team combat the time it takes for the shooter wheels to get up to speed?](https://www.chiefdelphi.com/t/how-does-your-team-combat-the-time-it-takes-for-the-shooter-wheels-to-get-up-to-speed/455716)
- [ ] auto turn to angle to collect nodes on other side of field and/or driver cam to help alignment when collecting?
- [ ] Manually focus OV9821 to detect tags from farther away? (recalibrate after lens twisting)
- [ ] Dynamic standard deviation updating for pose estimation
- [ ] [Multi-Camera Setup with PhotonVision’s Pose Estimator](https://www.chiefdelphi.com/t/multi-camera-setup-and-photonvisions-pose-estimator-seeking-advice/431154)
- [ ] hot glue/gaff tape the lens so it doesn’t move and change distortion properties with focus
- [x] collector camera
- [x] Shooter FF tuning
- [x] Shooter velocity P tuning
- [x] Shooter tilt PID (jittery/not smooth rn)
- [x] [Shooter tilt ProfiledPIDController (maybe need to do hold with FF?)](https://www.chiefdelphi.com/t/spark-flex-run-to-position/456098)
- [x] Collector/Shooter feeder logic
- [x] Shooter elevator position tuning (need to install hall effects)
- [x] Test shooter elevator
- [x] Climbing position PID tuning (need to install hall effects)
- [x] Collect values for shooter regression
- [x] [make DutyCycleEncoder.getAbsolutePosition() return it's result in degrees](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/wpilibj/DutyCycleEncoder.html#setDistancePerRotation(double))
